name: build
on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: build (all platforms)
    runs-on: ubuntu-18.04
    container:
      image: l.gcr.io/google/bazel:3.1.0
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: build (all platforms) 
        uses: ./.github/actions/build

